dispatcher:
  name: "default"
  concurrency_num: 1
datasets:
  - name: "gsm"
    data: "demo/gsm8k.json"
    prompt: "demo/prompt.yaml"
    prompt_type: "instruction"
    preprocess: "shuffle"
adapters:
  - name: "lora_0"
    type: "lora"
    path: "adapters/lora_sft_0"
    optimizer: "adamw"
    lr: 1e-5
    r: 16
    alpha: 64
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: true
      down_proj: true
      up_proj: true
  - name: "lora_1"
    type: "lora"
    path: "adapters/lora_sft_1"
    optimizer: "adamw"
    lr: 1e-5
    r: 4
    alpha: 64
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: true
      down_proj: true
      up_proj: true
  - name: "lora_2"
    type: "lora"
    path: "adapters/lora_sft_2"
    optimizer: "adamw"
    lr: 1e-5
    r: 4
    alpha: 64
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: true
      down_proj: true
      up_proj: true
  - name: "lora_3"
    type: "lora"
    path: "adapters/lora_sft_3"
    optimizer: "adamw"
    lr: 1e-5
    r: 32
    alpha: 64
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: true
      down_proj: true
      up_proj: true
tasks:
  - type: "train"
    name: "task_0"
    adapter: "lora_0"
    dataset: "gsm"
    batch_size: 8
    mini_batch_size: 4
    num_epochs: 500
    cutoff_len: 512
    save_step: 999999999
  - type: "train"
    name: "task_1"
    adapter: "lora_1"
    dataset: "gsm"
    batch_size: 4
    mini_batch_size: 2
    num_epochs: 300
    cutoff_len: 512
    save_step: 999999999
  - type: "train"
    name: "task_2"
    adapter: "lora_2"
    dataset: "gsm"
    batch_size: 16
    mini_batch_size: 8
    num_epochs: 300
    cutoff_len: 512
    save_step: 999999999
  - type: "train"
    name: "task_3"
    adapter: "lora_3"
    dataset: "gsm"
    batch_size: 4
    mini_batch_size: 2
    num_epochs: 1500
    cutoff_len: 1024
    save_step: 999999999
