dispatcher:
  name: "default"
  concurrency_num: 2

datasets:
  - name: "patent_data"
    data: "ccdv/patent-classification"
    data_type: "huggingface"
    subset: "patent"
    prompt: "demo/prompt.yaml"
    prompt_type: "instruction"
    preprocess: "shuffle"
    text_column: "text"
    label_column: "label"
    instruction: "Classify the following patent text into one of the IPC classes:"
    input_template: "Patent text: {text}"
    output_template: "IPC class: {label}"

adapters:
  - name: "patent_classifier_lora"
    type: "lora"
    path: "adapters/patent_classifier"
    optimizer: "adamw"
    lr: 3e-4
    r: 32
    alpha: 64
    dropout: 0.05
    target_modules:
      q_proj: true
      k_proj: true
      v_proj: true
      o_proj: true
      gate_proj: false
      down_proj: false
      up_proj: false

tasks:
  - type: "train"
    name: "patent_classification_task"
    adapter: "patent_classifier_lora"
    dataset: "patent_data"
    batch_size: 64
    mini_batch_size: 64
    num_epochs: 10
    cutoff_len: 256
    save_step: 2000 