dispatcher:
  type: "train"
  name: "patent_classification_dispatcher"
  device: "cuda:0"
  precision: "fp32"
  batch_size: 8
  mini_batch_size: 2
  accumulate_step: 4
  num_epochs: 3
  cutoff_len: 512
  save_step: 1000
  compute_cost: 8.0

datasets:
  patent_train:
    name: "patent_train"
    type: "train"
    data_path: "data/patent/train.json"
    preprocess: "shuffle"
    text_column: "text"
    label_column: "label"
  
  patent_validation:
    name: "patent_validation"
    type: "train"
    data_path: "data/patent/validation.json"
    preprocess: "default"
    text_column: "text"
    label_column: "label"

adapters:
  patent_classifier_lora:
    name: "patent_classifier_lora"
    type: "lora"
    rank: 8
    alpha: 16
    dropout: 0.1
    target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
    bias: "none"
    task_type: "CAUSAL_LM"

tasks:
  patent_train_task:
    type: "train"
    name: "patent_train_task"
    adapter: "patent_classifier_lora"
    dataset: "patent_train"
  
  patent_validation_task:
    type: "train"
    name: "patent_validation_task"
    adapter: "patent_classifier_lora"
    dataset: "patent_validation" 